title: Awesome title
author: Saman
email: samantaghavisani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an awesome description for new site.
# social links
twitter_username: saman-taghavi # DO NOT include the @ character, or else the build will fail!
github_username:  saman-taghavi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# theme
theme: minima
